engines:
  coffeelint:
    enabled: true
  scss-lint:
      enabled: true
      checks:
        VendorPrefix:
          enabled: false
  duplication:
      enabled: true
      config:
        languages:
        - ruby
        - javascript
ratings:
  paths:
    - "**.coffee"
    - "**.rb"
    - "**.haml"
    - "**.js"
    - "**.css"
    - "**.scss"
exclude_paths:
- db/
- "app/assets/javascripts/nv.d3.js"
- "app/assets/javascripts/d3.js"
- "app/assets/javascripts/bootstrap.min.js"
- "app/assets/javascripts/ui-bootstrap-tpls-0.11.2.js"
- "app/assets/javascripts/angular/animate.js"
- "app/assets/javascripts/angular/modules/angularjs-nvd3-directives.js"
- "app/assets/javascripts/angular/modules/angular.audio.js"
- "app/assets/javascripts/angular/modules/angular_ui_router.js"
- "lib/tasks/cucumber.rake"
- "app/assets/stylesheets/nv.d3.css"
- "app/assets/stylesheets/amelia.theme.bootsrap.css.scss"
