engines:
  coffeelint:
    enabled: true
  duplication:
      enabled: true
      config:
        languages:
        - ruby
        - javascript
ratings:
  paths:
    - "**.coffee"
exclude_paths:
- "app/assets/javascripts/nv.d3.js"
- "app/assets/javascripts/d3.js"
- "app/assets/javascripts/bootstrap.min.js"
- "app/assets/javascripts/ui-bootstrap-tpls-0.11.2js"
- "app/assets/javascripts/angular/animate.js"
- app/assets/javascripts/angular/modules/