engines:
  coffeelint:
    enabled: true
  scss-lint:
      enabled: true
      checks:
        VendorPrefix:
          enabled: false
        DeclarationOrder:
          enabled: false
        HexLength:
          enabled: false
        ColorKeyword:
          enabled: false
        ColorVariable:
          enabled: false
        PropertySortOrder:
          enabled: false
        EmptyLineBetweenBlocks:
          enabled: false
        FinalNewline:
          enabled: false
  duplication:
      enabled: true
      config:
        languages:
        - ruby
        - javascript
ratings:
  paths:
    - "**.coffee"
    - "**.rb"
    - "**.haml"
    - "**.js"
    - "**.css"
    - "**.scss"
exclude_paths:
- db/
- vendor/
- "lib/tasks/cucumber.rake"
